# Generated by Django 3.2.7 on 2021-09-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('title', models.CharField(help_text='文章标题', max_length=256, verbose_name='文章标题')),
                ('body', models.TextField(help_text='文章正文', verbose_name='文章正文')),
            ],
            options={
                'verbose_name': '公共字段表',
                'abstract': False,
            },
        ),
    ]
