# Generated by Django 3.2.7 on 2021-09-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('article', '0006_auto_20210904_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='articles', to='tag.Tag', verbose_name='文章标签'),
        ),
    ]
