# Generated by Django 3.2.7 on 2021-09-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag',
            new_name='tags',
        ),
    ]
