# Generated by Django 3.2.7 on 2021-09-07 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
        ('article', '0010_auto_20210907_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='avatar',
            field=models.ForeignKey(blank=True, help_text='文章标题背景图ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='avatar.avatar', verbose_name='文章标题背景图ID'),
        ),
    ]
