# Generated by Django 3.2.7 on 2021-09-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='标签名称', max_length=128, verbose_name='标签名称'),
        ),
    ]
