# Generated by Django 3.2.7 on 2021-09-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('url', models.URLField(help_text='文章标题背景图URL外链', max_length=256, verbose_name='文章标题背景图URL外链')),
            ],
            options={
                'verbose_name': '文章标题背景图',
                'verbose_name_plural': '文章标题背景图',
                'db_table': 'avatar_info',
            },
        ),
    ]
